name       : haskell-colour
version    : 2.3.4
release    : 2
source     :
    - https://hackage.haskell.org/package/colour-2.3.4/colour-2.3.4.tar.gz : 0f439f00b322ce3d551f28a4dd1520aa2c91d699de4cdc6d485b9b04be0dc5eb
license    : MIT
component  : programming.haskell
summary    : This package provides a data type for colours and transparency.
description: |
    This package provides a data type for colours and transparency. Colours can be blended and composed. Various colour spaces are supported. A module of colour names (Data.Colour.Names) is provided.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
