name       : haskell-colour
version    : 2.3.5
release    : 3
source     :
    - https://hackage.haskell.org/package/colour-2.3.5/colour-2.3.5.tar.gz : 3b8d471979617dce7c193523743c9782df63433d8e87e3ef6d97922e0da104e7
license    : MIT
component  : programming.haskell
summary    : This package provides a data type for colours and transparency.
description: |
    This package provides a data type for colours and transparency. Colours can be blended and composed. Various colour spaces are supported. A module of colour names (Data.Colour.Names) is provided.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
